#!/usr/bin/env python
# -*- coding:UTF-8 -*-
import os
from PIL import Image
def get(basedir):
    type = ['哈哈哈','新建文件夹','呀呀呀']
    for i in type:
        for ii in os.listdir(basedir+'\\'+i):
            for root, dirs, files in os.walk(basedir+i+"\\"+ii):
                print(root)
                for name in files:
                    #print('<fsfds>'+name+'<\\fsdfds>'+str(getatt(os.path.split(root))))
                    print('<fsfds>' + name + '<\\fsdfds>' )


def getatt(path):
    img = Image.open(path)
    imgSize = img.size
    print(imgSize)

get("D:\\text\\")
aaa="D:\text\哈哈哈\type1\1519118152124.jpg"
getatt(aaa)
