#!/usr/bin/python
import os
from PIL import Image
import smtplib
from email.header import Header
from email.utils import formataddr
from email.mime.text import MIMEText

mail_host = "smtp.qq.com"
mail_user = "*******@qq.com"
mail_password = "*********"
sender = "*******@qq.com"
receivers = "********@qq.com"

def getatt(path):
    img = Image.open(path)
    imgSize = img.size
    return imgSize

def tempFile(contents):
    with open('tmp.log','a') as f:
        f.write(str(contents))

def send_mail(Contents):

    message = MIMEText(Contents, 'plain', 'utf-8')
    message['From'] = formataddr(['发件人昵称',mail_user])
    message['To'] = formataddr(['收件人昵称',receivers])
    message["Subject"] = Header("邮件测试", "utf-8")
    try:
        server = smtplib.SMTP_SSL(mail_host,465)
        server.login(mail_user,mail_password)
        server.sendmail(sender,receivers,message.as_string())
        server.quit()
        print("send email success")
    except smtplib.SMTPException as err:
        print("send email fail")
        print("Error message:",err)

def get(basedir,imgeId):

    type = ['Directory1','Directory2','Directory3']
    for i in type:
        for ii in os.listdir(basedir+'\\'+i):
            for root, dirs, files in os.walk(basedir+i+"\\"+ii):
                for name in os.walk(root):
                    if len(os.listdir(root)) == 0:
                        continue
                    print(root)
                    tempFile(root + "\n")
                    imgeId = imgeId+1
                for name in files:
                    Imgtuple = getatt(root+'\\'+name)
                    imgCode = '''<img src="http://img.pargirl.com/%s/%s" width="%s" height="%s" class="alignnone size-full" />'''
                    print(imgCode%(imgeId,name,Imgtuple[0],Imgtuple[1]))
                    imgCodeTxt = imgCode %(imgeId, name, Imgtuple[0], Imgtuple[1])
                    tempFile(imgCodeTxt+"\n")
    with open('tmp.log','r') as ff:
     return   ff.read()

if __name__ == '__main__':
    send_mail(get("D:\\text\\", 0))
    os.remove('tmp.log')

