#!/usr/bin/env python
# -*- coding: utf-8 -*-
import urllib.request
import urllib.parse
from urllib import  error

def get_page(url):

    hearder={'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'}
    try:
        request=urllib.request.Request(url,headers=hearder)
        reponse=urllib.request.urlopen(request).read()
        #fhandle = open("D:\\xx\index.html", "wb")
        #fhandle.write(reponse)
        #fhandle.close()
    except error.HTTPError as errorinfo:
        print(errorinfo.code())

    return reponse




if __name__ == '__main__':
    value= get_page('http://www.mm131.com')
    strr= str(value, encoding='GBK')
    print(strr)

