#!/usr/bin/python
    import argparse
    import os
    import sys
    import datetime

    parser = argparse.ArgumentParser()
    parser.add_argument('integers', metavar='N', type=int, nargs='+',help='an integer for the accumulator')
    parser.add_argument('-e', action='store', dest='environment',help='Specified environment')
    parser.add_argument('-p', action='store', dest='platform',help='Specified a platform')
    parser.add_argument('-job', action='store',dest='project', help='Specified a project name')
    parser.add_argument('-version', action='version', version='%(prog)s 1.0')
    results = parser.parse_args()
    environment = results.environment
    platform = results.platform
    project = results.project

    class Animal(object):
        pass
